### ISSUE TITLE
validate_crypt does not work with dollar-sign characters and has script injection issues

### ISSUE THREAD

**Issue by blevine** [andris9/pass#6]
If the password contains a '$' character, the crypt check will fail.  This is because validate_crypt constructs an openssl command line and execs it.  The $whatever is interpreted as a variable by the shell.

Also, this code is vulnerable to a script injection attack.  For example, if the user enters ';rm *' somewhere in the password.

**Comment by andris9** [comment]
Fixed with b2897ee69e367b07bc8a56981262e13d9579d8b8 – uses spawn arguments array instead of exec string to run a command.
